DELETE http://localhost:3003/api/blogs/6537dd20c2f276946e6fd6b0
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY1NGEyYmYxMmY5NmM1NzU5YzZjNzdlMiIsImlhdCI6MTcwNTQ4MTAxNSwiZXhwIjoxNzA1NDg0NjE1fQ.BV47OOMpXMU4xQ8MuNfov_fym9IS-Q85Y6FUFdoanHA